<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KUCY2QTP01" name="com.PaymentCenterTestCases.PaymentCenterTestClass" tests="10" failures="0" timestamp="29 Apr 2016 14:43:35 GMT" time="661.899" errors="10">
  <testcase name="Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment" time="7.282" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_2_LaunchPaymentCenter_from_Portal_Make_CC_Payment -->
  <testcase name="Scenario_3_MakeECheck_PaymentwithPortalCredential" time="5.750" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_3_MakeECheck_PaymentwithPortalCredential(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_3_MakeECheck_PaymentwithPortalCredential -->
  <testcase name="Scenario_11_EmployeeSiteReports" time="108.502" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown , Excep Msg: Timed out after 90 seconds waiting for presence of element located by: By.xpath: .//select[@id=&#039;ctl00_CPL_Main_ctlReportFilter_uclSchools_drpSchool&#039;]
Build info: version: &#039;2.48.2&#039;, revision: &#039;41bccdd&#039;, time: &#039;2015-10-09 19:59:12&#039;
System info: host: &#039;KUCY2QTP01&#039;, ip: &#039;10.78.4.89&#039;, os.name: &#039;Windows 2003&#039;, os.arch: &#039;x86&#039;, os.version: &#039;5.2&#039;, java.version: &#039;1.7.0_80-ea&#039;
Session ID: 680f1246-7be9-435d-9750-0d74e8ecc07a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}] expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown , Excep Msg: Timed out after 90 seconds waiting for presence of element located by: By.xpath: .//select[@id='ctl00_CPL_Main_ctlReportFilter_uclSchools_drpSchool']
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'KUCY2QTP01', ip: '10.78.4.89', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.7.0_80-ea'
Session ID: 680f1246-7be9-435d-9750-0d74e8ecc07a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}] expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.Reports(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_11_EmployeeSiteReports(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_11_EmployeeSiteReports -->
  <testcase name="Scenario_6_ForgotPassword" time="14.641" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown . Excep msgUnable to connect database, Excep Msg: The connection to the host KUCY2DPAYSQL01, named instance paymentcenter failed. Error: &quot;java.net.SocketTimeoutException: Receive timed out&quot;. Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host. expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown . Excep msgUnable to connect database, Excep Msg: The connection to the host KUCY2DPAYSQL01, named instance paymentcenter failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host. expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.Forgotpassword(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_6_ForgotPassword(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_6_ForgotPassword -->
  <testcase name="Scenario_9_SearchStudentInEmployeeSite" time="375.098" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown in SearhcStudent method. Excep msg : Excep thrown in search student. Excpe Msg : Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;.//input[@id=&#039;ctl00_CPL_Main_Textid&#039;]&quot;}
Command duration or timeout: 90.03 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: &#039;2.48.2&#039;, revision: &#039;41bccdd&#039;, time: &#039;2015-10-09 19:59:12&#039;
System info: host: &#039;KUCY2QTP01&#039;, ip: &#039;10.78.4.89&#039;, os.name: &#039;Windows 2003&#039;, os.arch: &#039;x86&#039;, os.version: &#039;5.2&#039;, java.version: &#039;1.7.0_80-ea&#039;
*** Element info: {Using=xpath, value=.//input[@id=&#039;ctl00_CPL_Main_Textid&#039;]}
Session ID: 680f1246-7be9-435d-9750-0d74e8ecc07a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}] expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown in SearhcStudent method. Excep msg : Excep thrown in search student. Excpe Msg : Unable to locate element: {"method":"xpath","selector":".//input[@id='ctl00_CPL_Main_Textid']"}
Command duration or timeout: 90.03 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'KUCY2QTP01', ip: '10.78.4.89', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.7.0_80-ea'
*** Element info: {Using=xpath, value=.//input[@id='ctl00_CPL_Main_Textid']}
Session ID: 680f1246-7be9-435d-9750-0d74e8ecc07a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}] expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.SearchStudent(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_9_SearchStudentInEmployeeSite(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_9_SearchStudentInEmployeeSite -->
  <testcase name="Scenario_4_makeOnetimePaymentwithoutLogin" time="108.079" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Error occured, Excep msg Timed out after 90 seconds waiting for presence of element located by: By.xpath: .//select[@id=&#039;ctl00_CPL_Main_ucStudentInfo_ucl_Schooldrp1_drpSchool&#039;]
Build info: version: &#039;2.48.2&#039;, revision: &#039;41bccdd&#039;, time: &#039;2015-10-09 19:59:12&#039;
System info: host: &#039;KUCY2QTP01&#039;, ip: &#039;10.78.4.89&#039;, os.name: &#039;Windows 2003&#039;, os.arch: &#039;x86&#039;, os.version: &#039;5.2&#039;, java.version: &#039;1.7.0_80-ea&#039;
Session ID: 680f1246-7be9-435d-9750-0d74e8ecc07a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error occured, Excep msg Timed out after 90 seconds waiting for presence of element located by: By.xpath: .//select[@id='ctl00_CPL_Main_ucStudentInfo_ucl_Schooldrp1_drpSchool']
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'KUCY2QTP01', ip: '10.78.4.89', os.name: 'Windows 2003', os.arch: 'x86', os.version: '5.2', java.version: '1.7.0_80-ea'
Session ID: 680f1246-7be9-435d-9750-0d74e8ecc07a
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=WINDOWS, acceptSslCerts=true, javascriptEnabled=true, cssSelectorsEnabled=true, databaseEnabled=true, browserName=firefox, handlesAlerts=true, nativeEvents=false, webStorageEnabled=true, rotatable=false, locationContextEnabled=true, applicationCacheEnabled=true, takesScreenshot=true, version=35.0.1}] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.makeOneTimePaymentwithoutLogin(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_4_makeOnetimePaymentwithoutLogin(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_4_makeOnetimePaymentwithoutLogin -->
  <testcase name="Scenario_1_MakeCCPaymentwithPortalCredential" time="14.562" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_1_MakeCCPaymentwithPortalCredential(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_1_MakeCCPaymentwithPortalCredential -->
  <testcase name="Scenario_8_ChangePassword" time="14.610" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown. Excep msg Unable to connect database, Excep Msg: The connection to the host KUCY2DPAYSQL01, named instance paymentcenter failed. Error: &quot;java.net.SocketTimeoutException: Receive timed out&quot;. Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host. expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown. Excep msg Unable to connect database, Excep Msg: The connection to the host KUCY2DPAYSQL01, named instance paymentcenter failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host. expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.ChangePasswordofPaymentCenterProfile(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_8_ChangePassword(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_8_ChangePassword -->
  <testcase name="Scenario_10_EcheckEnableDisable" time="5.328" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_10_EcheckEnableDisable(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_10_EcheckEnableDisable -->
  <testcase name="Scenario_5_FeeTypePaymentFromEmployeeSite" time="8.047" classname="com.PaymentCenterTestCases.PaymentCenterTestClass">
    <error type="java.lang.AssertionError" message="Exception thrown, logout from  Admin KU Portal. Excep Msg&#039;Webmail&#039; column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Exception thrown, logout from  Admin KU Portal. Excep Msg'Webmail' column not found in Student search result headers expected [true] but found [false] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.CommonFunctions.UtilityFunctionsClass.loggErrorFailure(Unknown Source)
	at com.PaymentCenterClass.PaymentCenterMethods.logintoAdminPortal_Reset_Password(Unknown Source)
	at com.PaymentCenterTestCases.PaymentCenterTestClass.Scenario_5_FeeTypePaymentFromEmployeeSite(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- Scenario_5_FeeTypePaymentFromEmployeeSite -->
</testsuite> <!-- com.PaymentCenterTestCases.PaymentCenterTestClass -->
